# Generated by Django 5.2.6 on 2025-09-20 23:44

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=django.db.models.fields.UUIDField, primary_key=True, serialize=False),
        ),
    ]
