# Generated by Django 5.2.6 on 2025-09-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO store_collection (title) VALUES ('collection1')",
            "DELETE FROM store_collection WHERE title='collection1'",
        )
    ]
