# Generated by Django 5.2.6 on 2025-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='product_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
