# Generated by Django 5.2.6 on 2025-09-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_collection_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='product_count',
        ),
    ]
