# Generated by Django 5.2.6 on 2025-09-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_orderitem_quintity_to_quantity'),
    ]

    operations = [
        # Intentionally left empty: schema changes were applied previously or manually.
    ]
