# Generated by Django 5.2.6 on 2025-09-18 11:23

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cart_cart_shared_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default=store.models.get_uncategorized_collection_pk, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collection'),
        ),
    ]
