# Generated by Django 5.2.6 on 2025-09-18 11:46

import django.db.models.deletion
import store.models
from django.db import migrations, models, connection


def drop_cart_shared_if_exists(apps, schema_editor):
    table = 'store_cart'
    col = 'cart_shared'
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",
            [table, col],
        )
        row = cursor.fetchone()
        if not row or not row[0]:
            return
        cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{col}`;")


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cart_cart_shared_remove_product_collection'),
    ]

    operations = [
        # Conditional drop for cart_shared (safe if it was already removed earlier)
        migrations.RunPython(drop_cart_shared_if_exists, migrations.RunPython.noop),

        # Avoid executing destructive RemoveField operations for product.Collection here; the
        # DB already contains the proper column/constraints. Update migration state only
        # so subsequent migrations (like AlterField below) see the field.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(lambda apps, schema_editor: None),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='collection',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collection'),
                ),
                migrations.AlterField(
                    model_name='product',
                    name='collection',
                    field=models.ForeignKey(default=store.models.get_uncategorized_collection_pk, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collection'),
                ),
            ],
        ),
    ]
