# Generated by Django 5.2.6 on 2025-09-18 19:33

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_make_fk_non_nullable_again'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_shared',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Collection',
        ),
        migrations.AlterField(
            model_name='collection',
            name='featured_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in', to='store.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default=store.models.get_uncategorized_collection_pk, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collection'),
        ),
    ]
