# Generated by Django 5.2.6 on 2025-09-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'ordering': ['tag__label']},
        ),
    ]
